/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courseworddqs;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import java.util.Random;

/**
 *
 * @author andrewbolton
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        loadComboSchools();
        loadComboTopics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cmbSchool = new javax.swing.JComboBox<>();
        cmbYear = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bntQuiz = new javax.swing.JButton();
        lblTopic = new javax.swing.JLabel();
        cmbTopics = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Team 24 Quiz!");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Team 24's Quiz Extravaganza!");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 6, -1, -1));

        cmbSchool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSchoolActionPerformed(evt);
            }
        });
        getContentPane().add(cmbSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 34, 143, -1));

        cmbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9" }));
        getContentPane().add(cmbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 67, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("School:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 38, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Year:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 71, -1, -1));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 216, 80, -1));

        jLabel4.setText("Admin Password:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 194, -1, -1));

        bntQuiz.setText("Start Quiz");
        bntQuiz.setToolTipText("");
        bntQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntQuizActionPerformed(evt);
            }
        });
        getContentPane().add(bntQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 145, -1, -1));

        lblTopic.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblTopic.setText("Topic:");
        getContentPane().add(lblTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 104, -1, -1));

        getContentPane().add(cmbTopics, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 100, 143, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courseworddqs/3.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-460, -70, 850, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        if (txtPassword.getText().trim().toLowerCase().equals("team24")) {
            AdminMenu menu = new AdminMenu();
            menu.setLocationRelativeTo(null);
            menu.setVisible(true);
            dispose();
        } else {
            System.out.print("WRONG");
            JOptionPane optionPane = new JOptionPane("Please Enter The Correct Password!", JOptionPane.WARNING_MESSAGE);
            JDialog dialog = optionPane.createDialog("Password Incorrect!");
            dialog.setAlwaysOnTop(true);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void cmbSchoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSchoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSchoolActionPerformed

    private void bntQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntQuizActionPerformed
        loadQuestions();
    }//GEN-LAST:event_bntQuizActionPerformed

    private void loadQuestions() {
        String fileName = "Questions.csv";

        File file = new File(fileName);
        ArrayList finals = new ArrayList();
        ArrayList themed_finals = new ArrayList();
        ArrayList bonus = new ArrayList();
        
        Random generator = new Random();
       
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstline = br.readLine().trim();
            String[] columns = firstline.split(",");

            Object[] lines = br.lines().toArray();

            for (int i = 0; i < lines.length; i++) {
                String line = lines[i].toString().trim();
                String[] dataRow = line.split(",");
                if (dataRow[7].equals(cmbTopics.getSelectedItem().toString()) && dataRow[8].equals("None")){
                    finals.add(dataRow);
                }
                if(dataRow[7].equals(cmbTopics.getSelectedItem().toString()) && dataRow[8].equals("Bonus")){
                    bonus.add(dataRow);
                }

            }

            if (finals.size() < 10) {
                JOptionPane.showMessageDialog(this, "There are only "
                        + finals.size() + " question(s) for "
                        + cmbTopics.getSelectedItem().toString());

            } else {      
            
                for (int i = 0; i < 10; i++) {
                    int selected = generator.nextInt(finals.size());
                    themed_finals.add(finals.get(selected));
                    finals.remove(selected);
                }
                
                TakeQuiz quiz = new TakeQuiz(themed_finals);
                quiz.setLocationRelativeTo(null);
                quiz.school = cmbSchool.getSelectedItem().toString();
                quiz.year = cmbYear.getSelectedItem().toString();
                quiz.bonus = bonus;
                quiz.setVisible(true);
            }
            
        } catch (Exception ex) {
            System.out.println("Error");
            ex.printStackTrace();

        }
        
    }

    public void loadComboSchools() {
        String filepath = "Schools.csv";

        File file = new File(filepath);
        ArrayList<String> schools = new ArrayList();

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            br.readLine();

            Object[] lines = br.lines().toArray();

            for (int i = 0; i < lines.length; i++) {
                String line = lines[i].toString().trim();
                line = line.substring(0, line.length() - 1);
                schools.add(line);
            }
        } catch (Exception ex) {
            System.out.println("Error");
        }

        cmbSchool.setModel(new DefaultComboBoxModel<>(schools.toArray(new String[schools.size()])));
    }

    public void loadComboTopics() {
        String filepath = "Questions.csv";

        File file = new File(filepath);

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            br.readLine();

            Object[] lines = br.lines().toArray();

            for (int i = 0; i < lines.length; i++) {
                String line = lines[i].toString().trim();
                String topic = line.split(",")[7];

                if (((DefaultComboBoxModel) cmbTopics.getModel()).getIndexOf(topic) == -1) {
                    cmbTopics.addItem(topic);
                }
            }
        } catch (Exception ex) {
            System.out.println("Error");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntQuiz;
    private javax.swing.JComboBox<String> cmbSchool;
    private javax.swing.JComboBox<String> cmbTopics;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
